### ISSUE TITLE
Student page

### ISSUE THREAD

**Issue by yurug** [ocaml-sf/learn-ocaml#109]
Create a page per student : 
- to observe student's progress in the exercises ;
- to allow exercise to be assigned specifically to that student ;
- to evaluate the skills he masters and the skills he has to work on.

**Comment by yurug** [comment]
Is the item "visualisation of the evolution of the evaluation" easy to implement?

**Comment by yurug** [comment]
The other items are implemented, right?

**Comment by AltGr** [comment]
- [x]    to observe student's progress in the exercises ;
- [x]    to allow exercise to be assigned specifically to that student ;
  Not actually available from the student page (it doesn't have a full listing of the exercises, that would be quite complex and risk conflicting with an open "teacher view" tab) ; but it's easily accessible from the teacher view.
- [x]    to evaluate the skills he masters and the skills he has to work on.
- [ ]    to download students submissions ;
  they are shown in a dedicated tab, but there is no download link at the moment. Adding a download link for just that solution would be very easy, adding one (e.g. zip) for all solutions at once would be more involved.
- [ ]    to visualise the evolution of the evaluation.
  that would be quite difficult, the mechanism to store the history isn't even merged yet, and after then we would still need to add another layer to actually retrieve older values, and finally an interface to visualise things from these older values.
  If we are just interested in the grades, though, another much simpler solution could be to store them in a (timestamp, grade) list instead of only keeping the latest entry. A "grade over time" graph wouldn't then be too difficult, for a single exercise or even globally.

Feedback on the stats we compute at the moment would be very welcome as well, I wasn't too sure what would be most useful. We currently have:
- the global average: average % grade over all exercises that are open to the student (or were as part of a terminated assignment)
- the % of attempted exercises within that same set
- the average grade over the attempted exercises
- the average grade over all open exercises requiring a specific skill
- the average grade over all open exercises focusing on a specific skill

In particular, I wasn't sure how the last two could be regrouped, so I left them separate, but I don't know if it's the best solution. Having one line per skill and two columns for the two categories could be another option.
