### ISSUE TITLE
Fresh installation of learn-ocaml issues an error

### ISSUE THREAD

**Issue by yurug** [ocaml-sf/learn-ocaml#17]
After a fresh installation of learn-ocaml with opam2, I get the following error:

```
yann➜teaching/learn-ocaml/learn-ocaml(master✗)» learn-ocaml                                                                      
Updating app at ./www
Fatal: (Sys_error "./tutorials: No such file or directory")
Cannot process exercises: (Sys_error "./exercises: No such file or directory")
```

with no command provided, learn-ocaml should probably simply exit silently with a success status.

**Comment by AltGr** [comment]
There is still some UI and error handling work to do :)
The default commands are `build serve`, but without `--repo`, it will default to `./`. Here the error is simply that no repository was found there (a repository being expected to contain `tutorials/`, `lessons/` and `exercises/` subdirectories).

Try `--repo demo-repository from the project root`

**Comment by yurug** [comment]
with
```
learn-ocaml serve --repo demo-repository
```
(without doing ``learn-ocaml build --repo demo-repository`` before)

I get the following cryptic error:

![image](https://user-images.githubusercontent.com/448623/40721067-b6c619da-6418-11e8-8127-ad89138cbefe.png)

Then, if I do:
```
learn-ocaml build --repo demo-repository
learn-ocaml serve --repo demo-repository
```

I get a stalled page when I click on "Lessons":

![image](https://user-images.githubusercontent.com/448623/40721226-317439f0-6419-11e8-8e71-2c306b775de8.png)

**Comment by yurug** [comment]
The console says that some resources cannot be loaded (which is probably related to your latest PR).

**Comment by AltGr** [comment]
> `learn-ocaml serve --repo demo-repository`

As the doc says, `serve` assumes that the `www` dir has already been generated. I am wondering why you get anything at all, though ! Maybe a remnant of a previous run ? In any case, there certainly should be a safeguard against running the server if the app was not built.

Your last attempt should definitely have worked, and the failure seems to be due to missing files, indeed: as you point out it is probably because I moved them around. Did you re-run `opam install .` (or `make opaminstall`) to make sure that the static files are installed as expected ?

Thanks for the testing!

**Comment by AltGr** [comment]
Actually some stuff was not looked for at the proper place (and it was my installation which had stale files... which made it work!). Sorry, will have a fix shortly.
