### ISSUE TITLE
Installation windows

### ISSUE THREAD

**Issue by GUAGNODamien** [ocaml-sf/learn-ocaml#2]
Bonjour,
Je participe au projet PFITAXEl . Lors de l'installation de learn ocaml sur windows (j'ai installer opam a l'aide de  http://fdopen.github.io/opam-repository-mingw/). J'obtiens cette erreur.
Merci pour votre attention.
```
$ make
Compiler: ocaml 4.05.0
Warning: 13 old env warnings were not printed (add --env-warnings)
ocp-build: Entering directory `c:\Users\Damien\gui\learn-ocaml-editor'
Warning: 8 old project warnings were not printed (add --project-warnings)
File "c:\Users\Damien\gui\learn-ocaml-editor\src\app\build.ocp", line 1, charact              ers -1--1:
ocp-build: Leaving directory `c:\Users\Damien\gui\learn-ocaml-editor'
Error: in project "learnocaml-exercise", the source filename
        ".\_obuild\learnocaml-exercise\learnocaml-exercise.byte" does not exist
RULE 365 (state active)
                SOURCE .\_obuild\learnocaml-exercise\learnocaml-exercise validat              ed(not available)
                SOURCE .\_obuild\learnocaml-exercise\learnocaml-exercise.byte(no              t available)
        cd "c:\\Users\\Damien\\gui\\learn-ocaml-editor\\src\\app"
        js_of_ocaml +weak.js +cstruct/cstruct.js C:\Users\Damien\gui\learn-ocaml              -editor\.\src\ace-lib/ace_bindings.js C:\Users\Damien\gui\learn-ocaml-editor\.\_              obuild\learnocaml-exercise/learnocaml-exercise.byte
                TARGET .\_obuild\learnocaml-exercise\learnocaml-exercise.js
make: *** [Makefile:22: build] Error 2
```

**Comment by erikmd** [comment]
@yurug thanks for your feedback! As a workaround, the PFITAXEL members that use Windows are relying on a Linux VM (not Docker) to work on learn-ocaml-editor. But if they find it'd be more convenient to avoid the VM and work natively under Windows, we'll indeed be able to follow-up this issue with more details.
Cheers, Erik

**Comment by AltGr** [comment]
@erikmd I am working out how to best use docker containers for the different needs, and there are actually two main possibilities:

1. a docker container for the web-app: built-in exercise repository, use to run a server directly (how to handle persistent server-side data, e.g. user tokens and files, may remain a question though)
2. a docker container strictly for the `learn-ocaml` _program_, i.e. the manager, as introduced in #13. This means it's a bit more work to just start a working server, but on the other hand, it's much easier to use if you need control over your exercises repository: you need to have a local exercises/lessons/etc. repository, and from there run e.g. `docker run learn-ocaml` (with some additional bind-mount options). the program in the container will generate the web-app and serve it transparently, also syncing persistent server state to the local filesystem if needed.

The second option is more versatile and may be best to use from MS Windows, since it allows you to edit exercises etc. naturally on your system, without need to be concerned that `learn-ocaml` will actually run within Docker. The first option is probably quite useful as well, though. Note that Docker supports deriving images from others, so it would probably be possible to derive 1. from 2.

**Comment by erikmd** [comment]
@AltGr thanks for your remarks. BTW when you say

> Note that Docker supports deriving images from others, so it would probably be possible to derive 1. from 2.

maybe you could just as well devise a single Dockerfile relying on the [multi-stage builds feature](https://docs.docker.com/develop/develop-images/multistage-build/)?

Finally regarding your suggestion

> The second option is more versatile and may be best to use from MS Windows, since it allows you to edit exercises etc. naturally on your system

note that in the ["learn-ocaml-editor"](https://github.com/pfitaxel/learn-ocaml-editor) project we are not only looking at exercises' code, but also extending the web-app itself, so a mere `docker run learn-ocaml` wouldn't be sufficient (but admittedly we could have considered a Docker-based workflow, using `docker build -t learn-ocaml .` etc.)
