### ISSUE TITLE
A likely type inference problem of "Eval code".

### ISSUE THREAD

**Issue by dborisog** [ocaml-sf/learn-ocaml#377]
While going through the exercises available in the demo of the platform ( https://ocaml-sf.org/learn-ocaml-public/ ), a bug appeared while working on "Finding the Minimum" exercise, please see the screenshot attached to this report. 

Toplevel reports a type error while having no problem with running it on the toplevel and though the grading exercises. It seems type inference of "Eval code" is different to type inference of "Compil" and "Grade!", and the former misbehaves in this example.

![finding-the-minimum](https://user-images.githubusercontent.com/4368019/104090242-2e3c6900-527e-11eb-8a5e-5a28e1181020.png)

**Comment by erikmd** [comment]
Hi @dborisog, it seems you just forgotten to click on the `Reset` button to clean the toplevel environment (`Clear` is not enough).

As a result, the `min` function tested in your example was not the default function (from OCaml Stdlib), but is you own function `min` from the previous execution.

To sum up, there is no issue here and I guess one can close the issue. Please comment further or reopen if you think otherwise.
