### ISSUE TITLE
Bug: `learn-ocaml build` does not rebuild exercises with changes in dependencies listed in `depend.txt`

### ISSUE THREAD

**Issue by dm0n3y** [ocaml-sf/learn-ocaml#478]
Repro steps:
1. Set up an exercise with grader code dependencies in `depend.txt` as described in https://github.com/lsylvestre/learn-ocaml/blob/master/docs/tutorials/step-8.md. Get the exercise to build successfully using `learn-ocaml build`.
2. Make a breaking change in on the dependencies and rerun `learn-ocaml build`.
Expected result: failed build
Actual result: build command reports no changes

**Comment by dmoon1221** [comment]
As a temporary workaround, how can I clear the previously cached build state?

**Comment by erikmd** [comment]
Hi @dmoon1221, thanks a lot for your report!

> As a temporary workaround, how can I clear the previously cached build state?

I didn't attempt to reproduce it yet, but meanwhile, a workaround should just be to remove the `www` folder generated by `learn-ocaml build` (generally in the current directory), and run `learn-ocaml build` anew.

Let us know if this fixes the issue.

**Comment by dmoon1221** [comment]
Thanks! That was helpful. Specifically I wanted to clear the build cache for the specific exercise I was developing, so that I wouldn't have to wait to build every other exercise in our corpus to get feedback. I was able to do that by removing the exercise-specific json file within the `www` directory.

We're using our own fork of learn-ocaml, the tiny difference from current master being a modification to the compile button so that it also syncs the edit state.
